app5/urls.py
from django.conf.urls import url, include
from app5 import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'app5'

urlpatterns=[


      url(r'^register/', views.register, name='register'),
      url(r'^search/', views.search, name='search'),
      url(r'^user_login/', views.user_login, name='user_login'),
      url(r'user_status/(?P<username>[a-zA-Z0-9]+)$', views.user_status, name='user_status'),
      url(r'myprofile/(?P<username>[a-zA-Z0-9]+)$', views.profilepage, name='profilepage'),
      

]

chat/urls.py
from django.conf.urls import url
 
from chat import views

app_name = 'chatapp'
 
urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^chat/(?P<id>\d+)/$', views.chat_room, name='chat_room'),
]

pro5/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app5 import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

	url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^app5/', include('app5.urls')),
    url(r'^chats/', include('chat.urls')),
    url(r'^logout/',views.user_logout, name='logout'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app5/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
	"""docstring for ClassName"""
	user = models.OneToOneField(User)

	status = models.TextField(blank = True)
	desc = models.TextField(blank = True)
	portfolio_site = models.URLField(blank = True)
	profilepic = models.ImageField(blank = True, null = True, upload_to = 'profile_pics') 


	def __str__(self):
		return self.user.username

chat/models.py
from django.db import models
 
class ChatRoom(models.Model):
    name = models.CharField(max_length=200)
 
    def __unicode__(self):
    	return self.name
    
 

from django.contrib import admin
from chat.models import ChatRoom
 
admin.site.register(ChatRoom)

app5/forms.py
from django import forms
from django.contrib.auth.models import User
from app5.models import UserProfileInfo


class UserForm(forms.ModelForm):
	password = forms.CharField(widget =  forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('desc', 'portfolio_site', 'status', 'profilepic')

app5/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from app5.models import UserProfileInfo
from app5.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

# Create your views here.
def index(request):
	return render(request, 'html/index.html')
	
@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

def profilepage(request, username):
	#user = get_object_or_404(UserProfileInfo, user_username=username)
	#user1 = user.UserProfileInfo

	user = User.objects.get(username=username)
	return render(request, 'html/pp.html', {"user":user,})

def search(request):

	if (request.method == 'POST'):
		proname = request.POST.get('search')

		return redirect('app5:profilepage',username=proname)


def register(request):

	registered = False

	if request.method == 'POST':
		user_form = UserForm(data = request.POST)
		profile_form = UserProfileInfoForm(data = request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user

			if 'profilepic' in request.FILES:
				profile.profilepic = request.FILES['profilepic']

			profile.save()

			registered = True
		else:
			print(user_form.errors, profile_form.errors)

	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()

	return render(request, 'html/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):

	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse("Account not active.")

		else:
			print("Someone logged in and failed")
			print("Username: {} and password: {}".format(username, password))
			return HttpResponse("wrong, idiot.")

	else:
		return render(request,'html/login.html', {})

def user_status(request,username):

#	return HttpResponse("wrong, idiot.")

	if request.method == 'POST':
		mystatus = request.POST.get('status')
		user = User.objects.get(username=username)
		profile = user.userprofileinfo
		profile.status = mystatus
		profile.save()
		return redirect('app5:profilepage',username=username)
	    
		#trishla8 mypass8

chat/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
 
from chat.models import ChatRoom
 
def index(request):
  chat_rooms = ChatRoom.objects.order_by('name')[:5]
  context = {
    'chat_list': chat_rooms,
  }
  return render(request,'chatapp/index.html', context)
 
def chat_room(request, id):
  chat = get_object_or_404(ChatRoom, pk=id)
  return render(request, 'chatapp/chatroom.html', {'chat': chat})

templates/chatapp/chatroom.html
<!DOCTYPE html>
<html>
<head>
	<title>Mychatroom</title>
</head>
<body>
{% load staticfiles %}</pre>
<h1>{{ chat.name }}</h1>
<div id="message_list">
	<textarea></textarea>
</div>
<pre>
</body>
</html>

templates/chatapp/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Chat</title>
</head>
<body>
<h1>Chat here</h1>
{% if chat_list %}</pre>
<ul>
<ul>{% for chat in chat_list %}</ul>
</ul>
<ul>
<ul>
    <li><a id="" href="{% url 'chatapp:chat_room' chat.id %}"> {{ chat.name }}</a></li>
</ul>
</ul>
<ul>{% endfor %}</ul>
<pre>
 
 
 
{% else %}
 
No chats are available.
 
{% endif %}
</body>
</html>

templates/html/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Minimalistic</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="{% static "interact.js" %}"></script>
<style>
body{
	
	background-image: url({% static "bg.jpg" %});
	background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center; 
}


a{
	color: white;

}

</style>
</head>
<body>
<div class="bg" data-ibg-bg="{% static "bg.jpg" %}">
<nav class="navbar navbar-default navbar-static-top">
<div class="container">
<ul class="nav navbar-nav">
<li><a class="navbar-brand" href="{% url 'index' %}"> Home Page</a></li>
<li><a class="navbar-link" href="{% url 'admin:index' %}"> Admin</a></li>

<li><a class="navbar-link" href="{% url 'app5:register' %}"> Register</a></li>
 <li><form class="navbar-form" role="search" method="post" action="{% url 'app5:search' %}">
        <div class="input-group">
        {% csrf_token %}

            <input type="text" class="form-control" placeholder="Search" name="search">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
 </form></li>
{% if user.is_authenticated %}

 <li><a href= "{% url 'app5:profilepage' user.username %}">My Profile</a></li>
<li><a class="navbar-link" href="{% url 'logout' %}"> Logout</a></li>


{% else %}
<li><a class="navbar-link" href="{% url 'app5:user_login' %}"> Login</a></li>
{% endif %}

</ul> </div>
</nav>

{% block body_block %}
{% endblock %}

</body>

<script type="text/javascript">
	$(".bg").interactive_bg({
   strength: 25,
   scale: 1.05,
   animationSpeed: "100ms",
   contain: true,
   wrapContent: false
 });
</script>
</html>

templates/html/index.html
{% extends 'html/base.html' %}
{% block body_block %}




{% if user.is_authenticated %}
<div class="container">
<h3><center>Hi {{user.username}}!</center>
<form method="POST" action="{% url 'app5:user_status' user.username %}">
{% csrf_token %}
<div class="form-group">
      <label for="inputlg"></label>
      <input class="form-control input-lg" id="inputlg" type="text" name='status' placeholder="How are you feeling?">
    </div><center>
    <input type="submit" name='submitbtn' value='Add Status'>
    </center>
</form>
</h3>
</div>
{% else %}
<center>

<div class="container"><h3>You're not logged in, yet!</h3></div>
<br><br><br></br><br>
    <button type="button" class="btn btn-primary"><a href="{% url 'app5:register' %}">Register</a></button>
    OR
    <button type="button" class="btn btn-primary"><a href="{% url 'app5:user_login' %}">Login</a></button>

<!-- starts carousel -->
</center>
{% endif %}

{% endblock %}

templates/html/login.html
{% extends 'html/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'app5:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

templates/html/pp.html
{% extends 'html/base.html' %}
{% block body_block %}

<div class="jumbotron">
<b><h2>{{ user.username }}</h2></b>
<br><br>
{{ user.userprofileinfo.status }}
<br><br>
<h3>Email:</h3> {{ user.email }}
<br><br>

<h3>Social Handle:</h3> {{ user.userprofileinfo.portfolio_site }}
<br><br>

<h3>Description:</h3> {{ user.userprofileinfo.desc }}
<br><br>

<h3>Profile Picture:</h3> <img src="{{ user.userprofileinfo.profilepic.url|default_if_none:'#' }}"/>

</div>

{% endblock %}

templates/html/registration.html
{% extends 'html/base.html' %}
{% block body_block %}

<div class="jumbotron">
{% if registered %}
<h1>Thanks for registering</h1>
{% else %}
<h1>Register now.</h1>

<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" name="" value="Register">

</form>
{% endif %}

</div>

{% endblock %}